version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8999617581@Sh
      MYSQL_DATABASE: efir
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  your-app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/resources/application.properties
    environment:
      - SPRING_PROFILES_ACTIVE=default
